### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by fisk** [fisk/fisked#6]
So we can know if there are powerline patched fonts

**Comment by frangiz** [comment]
Generate one if not exists? Json format?

**Comment by fisk** [comment]
Yeah I want all available properties generated because that's the only documentation people are gonna have about what you can and can not do. If they are not generated, nobody is realistically gonna have a clue it's configurable.

**Comment by fisk** [comment]
And JSON sounds fine

**Comment by fisk** [comment]
Sweeeeeet
